Fix manage resumeable signedURL uploads
abhinav-qlogic/google-cloud-java pull request #1
Opened 2019-04-01 14:24 UTC by abhinav-qlogic

2019-04-01 17:00 UTC, pmakani requested changes

2019-04-01 17:00 UTC, pmakani commented on google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
> +import com.google.cloud.*;
Please use IDE settings that do not use * but rather use individual imports.

2019-04-01 17:00 UTC, pmakani commented on google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java
> +import java.util.*;
Please use IDE settings that do not use * but rather use individual imports.

2019-04-01 17:00 UTC, pmakani commented on google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
> +    return null;
why would you return `null` instead of any value ? .

2019-04-02 06:45 UTC, ajaaym requested changes

2019-04-02 06:45 UTC, ajaaym commented on google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/StorageRpc.java
> +   * Opens a resumable upload channel for a given storage object.
Opens a resumable upload channel for a given signUrl

2019-04-02 06:53 UTC, closed without merging