fix getCountEntities method added for Entity Count Query in DataStore
abhinav-qlogic/google-cloud-java pull request #5
Opened 2019-05-08 12:19 UTC by abhinav-qlogic

2019-05-08 13:45 UTC, ajaaym requested changes

2019-05-08 13:45 UTC, ajaaym commented on google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResults.java
> +  int getCountEntities();
why getCountEntities vs countEntities()?

2019-05-08 13:51 UTC, rahulKQL requested changes

2019-05-08 13:51 UTC, rahulKQL commented on google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResults.java
> +   * </pre>
Please replace `</pre>`  with  ` }</pre>`

2019-05-08 13:51 UTC, rahulKQL commented on google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResultsImpl.java
> +      count = runQueryResponsePb.getBatch().getSkippedResults();
Please extract `runQueryResponsePb.getBatch()` into a local variable

2019-05-09 09:33 UTC, abhinav-qlogic commented on google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResults.java
> +  int getCountEntities();
done

2019-05-09 09:33 UTC, abhinav-qlogic commented on google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResults.java
> +   * </pre>
done

2019-05-09 09:33 UTC, abhinav-qlogic commented on google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResultsImpl.java
> +      count = runQueryResponsePb.getBatch().getSkippedResults();
done

2019-05-17 13:20 UTC, closed without merging